Fix RangeItem component when there is only one item in the range
vtex-apps/app-store-price pull request #3
Opened 2020-09-02 17:24 UTC by pedromtec

#### What does this PR do? \*
Fix `RangeItem` component when there is only one item in the range
#### How to test it? \*
[workspace](https://pricenew--extensions.myvtex.com/vtex-google-shopping/p)

#### Related to / Depends on \*
[app-store-api](https://github.com/vtex/app-store-api/pull/20)

2020-09-03 18:33 UTC, arturpimentel requested changes

2020-09-03 18:33 UTC, arturpimentel commented on react/AppStorePrice.tsx
> +              ? undefined
Use `null` instead of `undefined` whenever possible. It's good practice to let `undefined` as naturally as possible, instead of assigning it to parameters yourself

2020-09-03 20:07 UTC, pedromtec commented on react/AppStorePrice.tsx
> +              ? undefined
I'm using an optional parameter 
```
  minQuantity?: number
  maxQuantity?: number
```

2020-09-03 20:08 UTC, pedromtec commented on react/AppStorePrice.tsx
> +              ? undefined
Do you think is it a good approach to change the type ? `minQuantity | null`

2020-09-08 14:05 UTC, arturpimentel approved these changes

2020-09-08 14:07 UTC, merged