Feat/checkout
vtex-apps/app-store-price pull request #7
Opened 2020-12-11 13:30 UTC by pedromtec

#### What does this PR do? \*

it allows to use the component at checkout.

#### How to test it? \*
Go to checkout and buy for  `pilateslovers` account.
[workspace](https://pedrocheckout--extensions.myvtex.com/agencian1-n1insightpro/p)

2020-12-11 18:19 UTC, arturpimentel requested changes

2020-12-11 18:19 UTC, arturpimentel commented on manifest.json
> +  "registries": ["smartcheckout"],
This is unnecessary
```suggestion
```

2020-12-11 18:19 UTC, arturpimentel commented on react/AppStorePrice.tsx
> +  const productId = product ? product.productId : orderForm.items[0].productId
Maybe we could isolate responsibilities by making two different components:
```jsx
function CheckoutPrice() {
  const {
    orderForm: {
      items: [{ productId }]
    }
  } = useOrderForm()

  return <AppStorePrice productId={productId} />
}

function ProductPrice() {
  const {
    product: { productId },
  } = useProduct()

  return <AppStorePrice productId={productId} />
}

function AppStorePrice({ productId }) {
  // old logic here
}
```
Then you could use a different block for each component and place them accordingly in our theme

2020-12-13 18:46 UTC, pedromtec commented on react/AppStorePrice.tsx
> +  const productId = product ? product.productId : orderForm.items[0].productId
It makes sense, but we need to release a major version.

2020-12-14 13:20 UTC, marlonguimaraes approved these changes

2020-12-15 13:47 UTC, pedromtec commented
> #### What does this PR do? *
> it allows to use the component at checkout.
> 
> #### How to test it? *
> Go to checkout and buy for `pilateslovers` account.
> [workspace](https://pedrocheckout--extensions.myvtex.com/agencian1-n1insightpro/p)

2020-12-15 15:00 UTC, arturpimentel approved these changes

2020-12-15 16:39 UTC, merged